#!/bin/sh
#
# custom dwm startup script
#
# author: Martin Ohmann <martin@mohmann.de>
#

# set font path
xset +fp /usr/share/fonts/local

# update font config
xset fp rehash

# load .Xresources and .Xdefaults
xrdb -merge $HOME/.Xresources
xrdb -merge $HOME/.Xdefaults

# init keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# export keyring globals
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# override style for QT applications
export QT_STYLE_OVERRIDE=gtk

# fix trackpoint issues
sudo $HOME/.local/bin/fixtp &

# lanuch polkit auth agent
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# set wallpaper
eval $(cat $HOME/.fehbg)
# lauch system tray
$HOME/.local/bin/trayer &

# lauch network manager applet
/usr/bin/nm-applet &

# launch xscreensaver daemon
/usr/bin/xscreensaver -no-splash &

# disable screensaver for fullscreen video
$HOME/.local/bin/lightsOn.sh 1190 &

# lauch music player daemon
#/usr/bin/mpd > /dev/null 2>&1 &

# launch owncloud
# /usr/bin/owncloud > /dev/null 2>&1 &

# launch dropbox
dropboxd > /dev/null 2>&1 &

# launch thunderbird
/usr/bin/thunderbird > /dev/null 2>&1 &

# set dircolors
eval $(dircolors -b $HOME/.dircolors)

# lauch compositor
/usr/bin/compton -CGb -f -D 5 --fade-exclude 'class_g = "trayer"' --backend glx

# lauch notification daemon
/usr/bin/dunst > /dev/null 2>&1 &

$HOME/.local/bin/dwm-status.rb > ~/.dwm-status.log 2>&1 &

# hacky: switch to external screen, if any. need to improve this sometime
(
	sleep 1
	if xrandr | grep "DP1 connected" > /dev/null 2>&1; then
		screenswitcher -s
		screenswitcher -s
		dwm-after-scsw
	fi
) &

while true; do 
  dwm 2> ~/.dwm.log
done
